#!/bin/bash
# ^^^^^^^^^^
# This is only to make correct editor highlighting.
#
# This file should be sourced from /etc/portage/env/$CATEGORY/$PACKAGE*
#
# It removes all installed *.a files (i.e. all static library data)
# To remove also the *.la files (the information needed to link them),
# use mv_rmstaticla, instead.

mv_rmstatic() {
	local f
	f=${PORTAGE_CONFIGROOT%/}/etc/portage/env/$CATEGORY/$PN*
	: ${ED:=$D}
	if [ -n "`find "$ED" -name '*.a' -print -quit`" ]
	then	einfo "mv's hack mv_rmstatic from $f"
		find "$ED" -name '*.a' -exec rm -v -- '{}' '+'
		einfo "mv's hack mv_rmstatic applied"
	else	die "mv's hack mv_rmstatic is redundant in $f"
	fi
}

post_src_install() {
	mv_rmstatic
}
